### PR TITLE
Set interpreter config to debug as well in evm.SetDebug and update tracing tests

### PR DESCRIPTION
**Pull request by eelanagaraj**
### Description
Debugging the failure of the test case `TestBlockTracingConcurrentMapAccess` and then later in the `tracers_test` suite in https://github.com/celo-org/celo-blockchain/pull/1978 led to the two following observations:
- in the `evm.SetDebug` function, we currently only set `evm.Config.Debug` but not `evm.interpreter.cfg.Debug`, but both of these are used in EVM execution code. Fixing this is necessary for the go native tracing implementation to work
- the `tracers_test` suite has been commented out for the past few years but now mostly work with the original geth tests

The debug setting issue seems to have arisen with an upstream merge where we changed EVM/interpreter initialization from passing the config by reference to passing by value. This caused the divergence in debug config values. For now, I opted by setting both debug config values in the setter function instead of reverting to passing by reference, since upstream still passes the config by value and I imagine this could lead to the exact same issue in the future (and minimizes the diff).

This PR:
- fixes the config debug setting here (so that this subtle change doesn't get buried in the larger PR & that CI passes)
- takes some of the `tracer_test` fixes from the go-native tracing PR and implements them here so we have a clearer signal of what expected values are before the native tracing implementation

### Tested
- tracing unit tests
- ensured that all the tracing tests pass with/without the Debug config change locally
- [x] testing on blockscout rc1staging (TODO -- manually check that differences in outputs make sense, and make sure this doesn't break anything unexpected with older transaction tracing)
- [ ] ran rosetta CLI checks for limited time with new blockchain node to check that balance reconciliation looks good

### Related Issues
Prep to get https://github.com/celo-org/celo-blockchain/pull/1978 into mergeable state

### Backwards compatibility
This changes the traces outputted, as this now does not trace calls when distributing fees or completing tobin transfer logic. This breaks from current tracing behavior, but seems consistent with previous (pre #1695) functionality and intended functionality (from the comments).

### CODE REVIEW

**Review by palango — COMMENTED** [review]
Looks good, thanks for digging so deep into this code!

Some comments:
- What about fixing this by passing the config as a reference?
- Does `TestTraceTransactionWithRegistryDeployed` fail without the prior commits fixing the flags?
- I'd merge some commits, so that the history gets a bit nicer.

**Comment by eelanagaraj** [comment]
@palango 🙏 
> What about fixing this by passing the config as a reference?
geth passes the config by value in `NewEVM` and wanted to minimize the diff there. In more recent commits, they have entirely gotten rid of passing the config to the interpreter (and instead just use the one). I figured it'd be best for now to contain the changes within the `SetDebug` function for now and ultimately move towards the geth solution of refactoring the entire interpreter/evm. (Also I was nervous that within a future upstream merge, this change could again come back in, whereas the SetDebug code is entirely Celo-specific). Lmk if that makes sense or if you still think it's preferable to go back to passing by value!

> Does TestTraceTransactionWithRegistryDeployed fail without the prior commits fixing the flags?
yes!

> I'd merge some commits, so that the history gets a bit nicer.
def, planning to squash merge this. I initially kept stuff in separate undo/redo steps to save CI results while testing (obvi overwrote those when rebasing master hehe). Happy to split things up to separate commits if squash-merging isn't an option! 😄

**Comment by palango** [comment]
> Lmk if that makes sense or if you still think it's preferable to go back to passing by value!

Makes a lot of sense, lets keep it like that for now.

Last question: How did you generate the updates in the tracer tests?

**Comment by eelanagaraj** [comment]
> Makes a lot of sense, lets keep it like that for now.

Sounds good!

> Last question: How did you generate the updates in the tracer tests?

I took most of the changes from the go-native tracer PR  -- basically, that PR got these tests runnable (they have been commented out for 4 years 😅 ). The idea was to get those tests runnable with input pre-/post- the fix (no changes -- they pass either way; this was also one of the reasons for the undo/redo in the commit history since I wanted to confirm this in CI in addition to locally). The hope is that with these tests added on master, we will have a bit stronger of a signal about the go-native tracer implementation (i.e. that PR should require no changes to the input files to get those cases running).

 For the JSON files:
- I tried to make the least amount of changes to get them running (i.e. usually change gas values in outputs)
- In a few cases the inputs simply didn't work (I tried everything I could think of to decode these including using the transaction formats from the commit when they were added, but couldn't find a way 😭), I used the files from geth with slight changes to outputs to get them running (thank you for that tip btw @palango !).

Happy to add clarification anywhere or lmk if you can think of additional steps to take regarding the native tracer changes! 🙏

**Comment by eelanagaraj** [comment]
@palango oop I also added one last TODO to the PR -- I won't merge this until after the blockscout results comparison for some txs & making sure that it doesn't break things. Then, blockscout outputs should be identical for the go-native tracer once this change is merged!

**Review by palango — APPROVED** [review]
Great, that all sounds good to me.
I really like the approach of fixing tests *before* the native tracer PR so that we can be confident that nothing changes.

**Pull request merged**
