### PR TITLE
Updates G2 point compression

### PR DESCRIPTION
**Pull request by kobigurk**
## Description

Handles exceptional cases better on G2 point compression.

## Backwards Compatibility

The change is backwards compatible besides exception cases, which seem to have a very low probability of occuring and have not occured.

### CODE REVIEW

**Comment by gakonst** [comment]
I had initially approved the PR against master https://github.com/celo-org/bls-zexe/pull/150/files.

These changes correspond to this branch https://github.com/celo-org/bls-zexe/commits/hotfix/rc1-compression-fix, which is basically a cherrypick of #150 on top of RC1.

**Comment by asaj** [comment]
@kobigurk can you fill out the rest of the PR? What are the backwards compatibility implications?

**Comment by gakonst** [comment]
@kobigurk think this can be closed now since #1022 is merged

**Comment by kobigurk** [comment]
Right, thanks!

**Pull request closed without merging**
