### PR TITLE
fix: nil curr var

### LINKED ISSUE #2134: Seg fault / panic syncing mainnet on v1.7.4
## Expected Behavior

Sync from genesis without panic

## Actual Behavior

Panic and geth terminated. Resumes syncing normally after restart.

## Steps to reproduce the behavior

Build celo-blockchain from source tag `v1.7.4`
Go: `go1.19.2.linux-arm64, dependency in custom Dockfile`
Docker: `24.0.2`
Running on: `Ubuntu 22.04.2 LTS ARM64`

Dockerfile:
```
FROM arm64v8/ubuntu:jammy as builder

RUN apt update && apt install gcc make musl-dev wget -y

RUN wget https://go.dev/dl/go1.19.2.linux-arm64.tar.gz
RUN rm -rf /usr/local/go && tar -C /usr/local -xzf go1.19.2.linux-arm64.tar.gz
ENV PATH $PATH:/usr/local/go/bin

ADD . /go-ethereum
WORKDIR /go-ethereum
RUN make geth-musl

FROM arm64v8/ubuntu:jammy
ARG COMMIT_SHA

COPY --from=builder /go-ethereum/build/bin/geth /usr/local/bin/
RUN echo $COMMIT_SHA > /version.txt
ADD scripts/run_geth_in_docker.sh /

EXPOSE 8545 8546 30303 30303/udp
ENTRYPOINT ["sh", "/run_geth_in_docker.sh"]

# Add some metadata labels to help programatic image consumption
ARG COMMIT=$COMMIT_SHA
ARG VERSION=""
ARG BUILDNUM=""

LABEL commit="$COMMIT" version="$VERSION" buildnum="$BUILDNUM"
```

## Backtrace
```
INFO [06-19\|13:17:04.423] Imported new chain segment               blocks=190  txs=1079  mgas=243.352 elapsed=8.336s    mgasps=29.192  number=18,830,021 hash=234037..f78e82 age=2mo2d1h  dirty=74.86MiB
--
INFO [06-19\|13:17:07.629] Sending val enode share msg to proxy     func=sendValEnodeShareMsgs       proxy peer="Peer 16331f68e399c8af 10.192.11.7:30503" valAddresses length=119
INFO [06-19\|13:17:07.630] Skipping sending ValEnodesShareMsg b/c not validating func=sendValEnodesShareMsg
INFO [06-19\|13:17:12.431] Imported new chain segment               blocks=169  txs=889   mgas=206.133 elapsed=8.008s    mgasps=25.740  number=18,830,190 hash=3cd7bb..1c429a age=2mo2d1h  dirty=75.76MiB
INFO [06-19\|13:17:20.441] Imported new chain segment               blocks=221  txs=1171  mgas=267.872 elapsed=8.010s    mgasps=33.439  number=18,830,411 hash=570d7c..095d89 age=2mo2d59m dirty=76.94MiB
INFO [06-19\|13:17:28.969] Imported new chain segment               blocks=199  txs=820   mgas=223.748 elapsed=8.527s    mgasps=26.240  number=18,830,610 hash=63997b..6b01d5 age=2mo2d43m dirty=76.46MiB
INFO [06-19\|13:17:36.971] Imported new chain segment               blocks=145  txs=573   mgas=211.915 elapsed=8.002s    mgasps=26.481  number=18,830,755 hash=e204e2..de3f67 age=2mo2d31m dirty=77.38MiB
INFO [06-19\|13:17:37.634] Sending val enode share msg to proxy     func=sendValEnodeShareMsgs       proxy peer="Peer 16331f68e399c8af 10.192.11.7:30503" valAddresses length=119
INFO [06-19\|13:17:37.634] Skipping sending ValEnodesShareMsg b/c not validating func=sendValEnodesShareMsg
INFO [06-19\|13:17:42.725] Imported new chain segment               blocks=245  txs=1128  mgas=244.124 elapsed=5.753s    mgasps=42.428  number=18,831,000 hash=6af2e0..cfc589 age=2mo2d11m dirty=79.62MiB
INFO [06-19\|13:17:42.726] Downloader queue stats                   receiptTasks=0 blockTasks=33151 itemSize=1.83KiB  throttle=8192
INFO [06-19\|13:17:43.728] Unindexing transactions                  blocks=1727 txs=39667 total=2048 elapsed=1.002s
INFO [06-19\|13:17:44.066] Unindexed transactions                   blocks=2048 txs=47208 tail=16,481,001 elapsed=1.340s
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xc44908]
goroutine 574387 [running]:
github.com/celo-org/celo-blockchain/contracts/currency.(*Currency).ToCELO(...)
github.com/celo-org/celo-blockchain/contracts/currency/currency.go:62
github.com/celo-org/celo-blockchain/miner.createConversionFunctions.func2(0x3c831c0a?, 0x4011eba400?)
github.com/celo-org/celo-blockchain/miner/block.go:380 +0x28
github.com/celo-org/celo-blockchain/core/types.NewTxWithMinerFee(0x401328e120, 0x4091e8fbd0, 0x4091e8fbe0)
github.com/celo-org/celo-blockchain/core/types/transaction.go:555 +0x88
github.com/celo-org/celo-blockchain/core/types.NewTransactionsByPriceAndNonce({0x1914680?, 0x405c819bb0}, 0x409b8fe1e0, 0x4091e8fbd0, 0x4091e8fbe0)
github.com/celo-org/celo-blockchain/core/types/transaction.go:609 +0x168
github.com/celo-org/celo-blockchain/miner.(*worker).constructPendingStateBlock(0x40029794a0, {0x1911e58, 0x403d4b1d40}, 0x40034d0a80)
github.com/celo-org/celo-blockchain/miner/worker.go:366 +0x408
github.com/celo-org/celo-blockchain/miner.(*worker).mainLoop.func1.2()
github.com/celo-org/celo-blockchain/miner/worker.go:415 +0x38
created by github.com/celo-org/celo-blockchain/miner.(*worker).mainLoop.func1
github.com/celo-org/celo-blockchain/miner/worker.go:414 +0x1f4
```
Chain/Network: `Mainnet`

### PR DESCRIPTION
**Pull request by kehiy**
### Description
I added an if statement to check the value of curr to make sure it doesn't panic.

### Related issues

- Fixes #2134

### CODE REVIEW

**Comment by karlb** [comment]
The situation is still to unclear for me to trust that this change fixes the situation:
* I still don't know how the panic in https://github.com/celo-org/celo-blockchain/issues/2134 really happened
* We don't have a test to reproduce the issue or to test the nil case that is handled in this PR
* I suspect that returning nil from toCeloFn will cause problems for the caller, as no nil was returned before. We also still lose the error returned from GetCurrency.

**Comment by kehiy** [comment]
> The situation is still too unclear for me to trust that this change fixes the situation:
> 
> * I still don't know how the panic in [Seg fault / panic syncing mainnet on v1.7.4 #2134](https://github.com/celo-org/celo-blockchain/issues/2134) really happened
> * We don't have a test to reproduce the issue or to test the nil case that is handled in this PR
> * I suspect that returning nil from toCeloFn will cause problems for the caller, as no nil was returned before. We also still lose the error returned from GetCurrency.

when we return a nil, we can make sure that the full node was not panicking.

**Comment by karlb** [comment]
> when we return a nil, we can make sure that the full node was not panicking.

Have you tested what happens when nil gets returned? Maybe it just panics higher up the stack?

If it does not panic, how does returning nil affect the transactions getting executed? Will transactions with a certain feeCurrency be free, will they revert, or does something else happen?

**Comment by kehiy** [comment]
> Have you tested what happens when nil gets returned? Maybe it just panics higher up the stack?
> 
> If it does not panic, how does returning nil affect the transactions getting executed? Will transactions with a certain fee currency be free, will they revert, or does something else happen?

when we return nil, if we have an error handling in higher layers it don,t panic or something else
but without error handling in higher layers we going to panic again or face with new issues.
this change just helps us to make sure the `createConversionFunctions` function will not panic and simply assign the issue to higher layers with error handling.

**Pull request closed without merging**
