### PR TITLE
fix #1927: upgrade btcd

### LINKED ISSUE #1927: upgrade dependency on github.com/btcsuite/btcd
## Description

github.com/btcsuite/btcd/btcec was split out of github.com/btcsuite/btcd in a recent version and requires some minor changes to upgrade

Long story short, this PR needs to be ported from go-ethereum: https://github.com/ethereum/go-ethereum/pull/24533

## Context

This is important for anyone importing celo-blockchain. If celo-blockchain doesn't upgrade, no user of celo-blockchain can either. There's more context in the go-ethereum PR

### PR DESCRIPTION
**Pull request by vikstrous2**
### Description

Upgrading some dependencies - see #1927
Ported https://github.com/ethereum/go-ethereum/pull/24533 and made some extra changes to make things work

### Other changes

Some changes ported from https://github.com/ethereum/go-ethereum/pull/24533 might not have been absolutely necessary (ex. fixing a typo)

### Tested

Existing tests

### Related issues

- Fixes #1927

### Backwards compatibility

According to #24533, the changes are perfectly compatible and affect only non-cgo builds anyway. Looks like celo-blockchain can't build without cgo yet, so this is definitely not going to be an issue.

### CODE REVIEW

**Comment by hbandura** [comment]
@vikstrous2 I haven't had time to review this yet, but could you resolve the conflicts still? Thanks

**Comment by vikstrous2** [comment]
Rebased. It seems like CI is not configured to run against PRs from forks?

**Comment by vikstrous2** [comment]
Bump? This is blocking us from being able to upgrade our btcd dependency (unless we fork celo-blockchain).

**Comment by piersy** [comment]
@vikstrous2 we've updated our CI config to run forked PRs, if you could merge master again and resolve the conflicts then we can see how CI fares.

**Pull request closed without merging**
