### PR TITLE
Update celo-bls-go dependency to v0.6.1

### PR DESCRIPTION
**Pull request by mstraka100**
### Description

As described in https://github.com/celo-org/celo-blockchain/pull/1898, relying on an older version v0.2.4 of celo-bls-go prevents compilation on M1 processors. Updating to v0.6.1 of this dependency should fix this issue, as it supports M1 processors. 

### Other changes

Updating celo-bls-go also allows for the use of BLS batch verification code added in v0.6.1

### Tested

Running tests in CI to ensure compatibility.

### Related issues

N/A

### Backwards compatibility

N/A

### CODE REVIEW

**Comment by piersy** [comment]
Coverage from tests in `./e2e_test/...` for `./consensus/istanbul/...` at commit 86ff9f7b3caadb6a802d5455043ad3f8b90b014a
<details><summary>coverage:  51.3% of statements across all listed packages</summary><br>
<pre>
coverage:  61.6% of statements in consensus/istanbul
coverage:  42.7% of statements in consensus/istanbul/announce
coverage:  55.9% of statements in consensus/istanbul/backend
coverage:   0.0% of statements in consensus/istanbul/backend/backendtest
coverage:  24.3% of statements in consensus/istanbul/backend/internal/replica
coverage:  70.2% of statements in consensus/istanbul/core
coverage:  50.0% of statements in consensus/istanbul/db
coverage:   0.0% of statements in consensus/istanbul/proxy
coverage:  64.4% of statements in consensus/istanbul/uptime
coverage:  51.8% of statements in consensus/istanbul/validator
coverage:  79.2% of statements in consensus/istanbul/validator/random
</pre>
CommentID: 9d9b9159ea
</details>

**Comment by palango** [comment]
I just tried building this locally and ran into the following. Is there some dependency that I'm missing?
```
# github.com/celo-org/celo-bls-go/bls
ld: warning: directory not found for option '-L/Users/paul/go/pkg/mod/github.com/celo-org/celo-bls-go@v0.2.7-0.20220802155348-9137669836be/bls/../libs/aarch64-apple-darwin'
ld: library not found for -lbls_snark_sys
clang: error: linker command failed with exit code 1 (use -v to see invocation)
util.go:46: Command failed "/opt/homebrew/Cellar/go@1.16/1.16.15/libexec/bin/go build -ldflags -X main.gitCommit=2a8455cc278955513c0569d4b9289ec6b0e14a45 -X main.gitDate=20220802 -s -trimpath -v -o /Users/paul/Projects/celo-blockchain/build/bin/abidump ./cmd/abidump", err: "exit status 2"
```

**Comment by piersy** [comment]
I'm also encountering an error when trying to build this. The error seems to have been introduced in the last commit, the previous commit is working for me.

```
 go build ./...
# github.com/karalabe/usb
In file included from ../../go/pkg/mod/github.com/karalabe/usb@v0.0.0-20190919080040-51dc0efba356/libs.go:50:
../../go/pkg/mod/github.com/karalabe/usb@v0.0.0-20190919080040-51dc0efba356/libusb/libusb/os/darwin_usb.c:253:39: warning: 'kIOMasterPortDefault' is deprecated: first deprecated in macOS 12.0 [-Wdeprecated-declarations]
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/IOKit.framework/Headers/IOKitLib.h:123:19: note: 'kIOMasterPortDefault' has been explicitly marked deprecated here
In file included from ../../go/pkg/mod/github.com/karalabe/usb@v0.0.0-20190919080040-51dc0efba356/libs.go:50:
../../go/pkg/mod/github.com/karalabe/usb@v0.0.0-20190919080040-51dc0efba356/libusb/libusb/os/darwin_usb.c:390:26: warning: 'kIOMasterPortDefault' is deprecated: first deprecated in macOS 12.0 [-Wdeprecated-declarations]
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/IOKit.framework/Headers/IOKitLib.h:123:19: note: 'kIOMasterPortDefault' has been explicitly marked deprecated here
In file included from ../../go/pkg/mod/github.com/karalabe/usb@v0.0.0-20190919080040-51dc0efba356/libs.go:50:
../../go/pkg/mod/github.com/karalabe/usb@v0.0.0-20190919080040-51dc0efba356/libusb/libusb/os/darwin_usb.c:441:60: warning: 'kIOMasterPortDefault' is deprecated: first deprecated in macOS 12.0 [-Wdeprecated-declarations]
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/IOKit.framework/Headers/IOKitLib.h:123:19: note: 'kIOMasterPortDefault' has been explicitly marked deprecated here
In file included from ../../go/pkg/mod/github.com/karalabe/usb@v0.0.0-20190919080040-51dc0efba356/libs.go:51:
../../go/pkg/mod/github.com/karalabe/usb@v0.0.0-20190919080040-51dc0efba356/hidapi/mac/hid.c:693:34: warning: 'kIOMasterPortDefault' is deprecated: first deprecated in macOS 12.0 [-Wdeprecated-declarations]
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/IOKit.framework/Headers/IOKitLib.h:123:19: note: 'kIOMasterPortDefault' has been explicitly marked deprecated here
# gopkg.in/olebedev/go-duktape.v3
In file included from _cgo_export.c:4:
debugger.go:23:13: warning: unused function '_duk_debugger_attach' [-Wunused-function]
# github.com/celo-org/celo-bls-go/bls
ld: warning: directory not found for option '-L/Users/piersy/go/pkg/mod/github.com/celo-org/celo-bls-go@v0.2.7-0.20220802155348-9137669836be/bls/../libs/x86_64-apple-darwin'
ld: library not found for -lbls_snark_sys
clang: error: linker command failed with exit code 1 (use -v to see invocation)
# github.com/celo-org/celo-blockchain/tests/fuzzers/vflux/debug
ld: warning: -no_pie is deprecated when targeting new OS versions
```

**Comment by palango** [comment]
Closing this as we don't plan to include this in the short term.

**Pull request closed without merging**
