### PR TITLE
Update to go 1.16

### LINKED ISSUE #1420: Upgrade client to use Go 1.16.x
## Description

With the release of Go 1.16, v1.14 is no longer maintained.  We should upgrade to 1.16.x or at least to 1.15.x.  Since a security release has been announced for March 10, 2021, that would be a good time to do a celo-blockchain release using a new version.  Note that v1.16 adds support for compiling on M1-based (ARM64) macs, and so is desirable from the point of view of developers with new mac machines.

I am not aware of anything that needs to be cherry-picked from upstream to have the client work with v1.15.  For v1.16, I found the following: https://github.com/ethereum/go-ethereum/pull/21785

### PR DESCRIPTION
**Pull request by trianglesphere**
### Description

This updates go-celo to golang 1.16.

Changes
* Update snappy to v3 (from v1). This was manual recreation of https://github.com/ethereum/go-ethereum/pull/21934
* Bump to go 1.16 in CI/docker/other places (upstream equivalent: https://github.com/ethereum/go-ethereum/pull/22351)
* Fix ABI tests (from prev upstream fix)
* Fix a panic in a discv5 test - this is a new implementation that is not currently being used.
* Rebased our bitcode fix on top of `golang.com/x/mobile` to fix an issue with `make ios`

### Tested

Unit tests & CI

### Related issues

- Fixes #1420

### CODE REVIEW

**Review by oneeman — APPROVED** [review]
Terrific!

**Comment by oneeman** [comment]
CI shows the ios build failing

**Comment by trianglesphere** [comment]
> CI shows the ios build failing

Looking into it atm. Looks like there was some update in go 1.16 that's messing with go.mod/go.sum files in a weird way.

**Comment by trianglesphere** [comment]
I think I've tracked it down to the fact that our version of go mobile is out of date with master and their upstream does create a go.sum file. If that doesn't resolve this there's another golang issue that looks similar that looks like it will be released with 1.16.3

**Pull request merged**
