### PR TITLE
Upgrade `celo-bls-go` To Allow `celo-blockchain` to build on Macbook M1s

### PR DESCRIPTION
**Pull request by keefertaylor**
### Description

As of the master commit today (`9a89ff8028996dbea3bf27500e5a7c2ed6266188`), attempting to build `celo-blockchain` via `make geth` on a Macbook M1 chip (GOOS=darwin GOARCH=arm64) results in the following errors, generated from the `celo-bls-go` package:

```
Undefined symbols for architecture arm64:
  "_aggregate_public_keys", referenced from:
      __cgo_81e5edcac56b_Cfunc_aggregate_public_keys in _x002.o
     (maybe you meant: __cgo_81e5edcac56b_Cfunc_aggregate_public_keys_subtract, __cgo_81e5edcac56b_Cfunc_aggregate_public_keys )
  "_aggregate_public_keys_subtract", referenced from:
      __cgo_81e5edcac56b_Cfunc_aggregate_public_keys_subtract in _x002.o
     (maybe you meant: __cgo_81e5edcac56b_Cfunc_aggregate_public_keys_subtract)
  "_aggregate_signatures", referenced from:
      __cgo_81e5edcac56b_Cfunc_aggregate_signatures in _x002.o
     (maybe you meant: __cgo_81e5edcac56b_Cfunc_aggregate_signatures)
  "_batch_verify_signature", referenced from:
      __cgo_81e5edcac56b_Cfunc_batch_verify_signature in _x002.o
     (maybe you meant: __cgo_81e5edcac56b_Cfunc_batch_verify_signature)
  "_compress_pubkey", referenced from:
      __cgo_81e5edcac56b_Cfunc_compress_pubkey in _x002.o
     (maybe you meant: __cgo_81e5edcac56b_Cfunc_compress_pubkey)
  "_compress_signature", referenced from:
      __cgo_81e5edcac56b_Cfunc_compress_signature in _x002.o
     (maybe you meant: __cgo_81e5edcac56b_Cfunc_compress_signature)
  "_deserialize_private_key", referenced from:
      __cgo_81e5edcac56b_Cfunc_deserialize_private_key in _x002.o
     (maybe you meant: __cgo_81e5edcac56b_Cfunc_deserialize_private_key)
  "_deserialize_public_key", referenced from:
      __cgo_81e5edcac56b_Cfunc_deserialize_public_key in _x002.o
     (maybe you meant: __cgo_81e5edcac56b_Cfunc_deserialize_public_key_cached, __cgo_81e5edcac56b_Cfunc_deserialize_public_key )
  "_deserialize_public_key_cached", referenced from:
      __cgo_81e5edcac56b_Cfunc_deserialize_public_key_cached in _x002.o
     (maybe you meant: __cgo_81e5edcac56b_Cfunc_deserialize_public_key_cached)
  "_deserialize_signature", referenced from:
      __cgo_81e5edcac56b_Cfunc_deserialize_signature in _x002.o
     (maybe you meant: __cgo_81e5edcac56b_Cfunc_deserialize_signature)
  "_destroy_private_key", referenced from:
      __cgo_81e5edcac56b_Cfunc_destroy_private_key in _x002.o
     (maybe you meant: __cgo_81e5edcac56b_Cfunc_destroy_private_key)
  "_destroy_public_key", referenced from:
      __cgo_81e5edcac56b_Cfunc_destroy_public_key in _x002.o
     (maybe you meant: __cgo_81e5edcac56b_Cfunc_destroy_public_key)
  "_destroy_signature", referenced from:
      __cgo_81e5edcac56b_Cfunc_destroy_signature in _x002.o
     (maybe you meant: __cgo_81e5edcac56b_Cfunc_destroy_signature)
  "_encode_epoch_block_to_bytes", referenced from:
      __cgo_81e5edcac56b_Cfunc_encode_epoch_block_to_bytes in _x002.o
     (maybe you meant: __cgo_81e5edcac56b_Cfunc_encode_epoch_block_to_bytes_cip22, __cgo_81e5edcac56b_Cfunc_encode_epoch_block_to_bytes )
  "_encode_epoch_block_to_bytes_cip22", referenced from:
      __cgo_81e5edcac56b_Cfunc_encode_epoch_block_to_bytes_cip22 in _x002.o
     (maybe you meant: __cgo_81e5edcac56b_Cfunc_encode_epoch_block_to_bytes_cip22)
  "_free_vec", referenced from:
      __cgo_81e5edcac56b_Cfunc_free_vec in _x002.o
     (maybe you meant: __cgo_81e5edcac56b_Cfunc_free_vec)
  "_generate_private_key", referenced from:
      __cgo_81e5edcac56b_Cfunc_generate_private_key in _x002.o
     (maybe you meant: __cgo_81e5edcac56b_Cfunc_generate_private_key)
  "_hash_composite", referenced from:
      __cgo_81e5edcac56b_Cfunc_hash_composite in _x002.o
     (maybe you meant: __cgo_81e5edcac56b_Cfunc_hash_composite)
  "_hash_direct", referenced from:
      __cgo_81e5edcac56b_Cfunc_hash_direct in _x002.o
     (maybe you meant: __cgo_81e5edcac56b_Cfunc_hash_direct)
  "_init", referenced from:
      __cgo_81e5edcac56b_Cfunc_init in _x002.o
     (maybe you meant: __cgo_81e5edcac56b_Cfunc_init, __cgo_wait_runtime_init_done )
  "_private_key_to_public_key", referenced from:
      __cgo_81e5edcac56b_Cfunc_private_key_to_public_key in _x002.o
     (maybe you meant: __cgo_81e5edcac56b_Cfunc_private_key_to_public_key)
  "_serialize_private_key", referenced from:
      __cgo_81e5edcac56b_Cfunc_serialize_private_key in _x002.o
     (maybe you meant: __cgo_81e5edcac56b_Cfunc_serialize_private_key)
  "_serialize_public_key", referenced from:
      __cgo_81e5edcac56b_Cfunc_serialize_public_key in _x002.o
     (maybe you meant: __cgo_81e5edcac56b_Cfunc_serialize_public_key_uncompressed, __cgo_81e5edcac56b_Cfunc_serialize_public_key )
  "_serialize_public_key_uncompressed", referenced from:
      __cgo_81e5edcac56b_Cfunc_serialize_public_key_uncompressed in _x002.o
     (maybe you meant: __cgo_81e5edcac56b_Cfunc_serialize_public_key_uncompressed)
  "_serialize_signature", referenced from:
      __cgo_81e5edcac56b_Cfunc_serialize_signature in _x002.o
     (maybe you meant: __cgo_81e5edcac56b_Cfunc_serialize_signature)
  "_sign_message", referenced from:
      __cgo_81e5edcac56b_Cfunc_sign_message in _x002.o
     (maybe you meant: __cgo_81e5edcac56b_Cfunc_sign_message)
  "_sign_pop", referenced from:
      __cgo_81e5edcac56b_Cfunc_sign_pop in _x002.o
     (maybe you meant: __cgo_81e5edcac56b_Cfunc_sign_pop)
  "_verify_pop", referenced from:
      __cgo_81e5edcac56b_Cfunc_verify_pop in _x002.o
     (maybe you meant: __cgo_81e5edcac56b_Cfunc_verify_pop)
  "_verify_signature", referenced from:
      __cgo_81e5edcac56b_Cfunc_verify_signature in _x002.o
     (maybe you meant: __cgo_81e5edcac56b_Cfunc_verify_signature, __cgo_81e5edcac56b_Cfunc_batch_verify_signature )
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

This incompatibility was documented in https://github.com/celo-org/celo-bls-go/issues/22 and fixed in https://github.com/celo-org/celo-bls-go/pull/25 on September 21, 2021. It was published in the `celo-bls-go` package on September 21, 2021. 

Currently, `celo-blockchain` relies on `celo-bls-go@0.2.4` which was published on November 19, 2020. By upgrading this library, `celo-blockchain` will now build on an M1 Macbook.

### Other changes

N/A

### Tested

Relying on CI tests in `celo-blockchain` to make sure this doesn't bring in incompatible changes. 

Tested that this build on an M1 by the following: 
```
$ make geth
env GO111MODULE=on go run build/ci.go install ./cmd/geth
>>> /opt/homebrew/Cellar/go/1.18.2/libexec/bin/go build -ldflags -X main.gitCommit=9a89ff8028996dbea3bf27500e5a7c2ed6266188 -X main.gitDate=20220511 -s -trimpath -v -o /Users/keefertaylor/nodes/keefer-celo-fork/celo-blockchain/build/bin/geth ./cmd/geth
# github.com/karalabe/usb
In file included from ../../go/pkg/mod/github.com/karalabe/usb@v0.0.0-20190919080040-51dc0efba356/libs.go:50:
../../go/pkg/mod/github.com/karalabe/usb@v0.0.0-20190919080040-51dc0efba356/libusb/libusb/os/darwin_usb.c:253:39: warning: 'kIOMasterPortDefault' is deprecated: first deprecated in macOS 12.0 [-Wdeprecated-declarations]
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/IOKit.framework/Headers/IOKitLib.h:123:19: note: 'kIOMasterPortDefault' has been explicitly marked deprecated here
In file included from ../../go/pkg/mod/github.com/karalabe/usb@v0.0.0-20190919080040-51dc0efba356/libs.go:50:
../../go/pkg/mod/github.com/karalabe/usb@v0.0.0-20190919080040-51dc0efba356/libusb/libusb/os/darwin_usb.c:390:26: warning: 'kIOMasterPortDefault' is deprecated: first deprecated in macOS 12.0 [-Wdeprecated-declarations]
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/IOKit.framework/Headers/IOKitLib.h:123:19: note: 'kIOMasterPortDefault' has been explicitly marked deprecated here
In file included from ../../go/pkg/mod/github.com/karalabe/usb@v0.0.0-20190919080040-51dc0efba356/libs.go:50:
../../go/pkg/mod/github.com/karalabe/usb@v0.0.0-20190919080040-51dc0efba356/libusb/libusb/os/darwin_usb.c:441:60: warning: 'kIOMasterPortDefault' is deprecated: first deprecated in macOS 12.0 [-Wdeprecated-declarations]
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/IOKit.framework/Headers/IOKitLib.h:123:19: note: 'kIOMasterPortDefault' has been explicitly marked deprecated here
In file included from ../../go/pkg/mod/github.com/karalabe/usb@v0.0.0-20190919080040-51dc0efba356/libs.go:51:
../../go/pkg/mod/github.com/karalabe/usb@v0.0.0-20190919080040-51dc0efba356/hidapi/mac/hid.c:693:34: warning: 'kIOMasterPortDefault' is deprecated: first deprecated in macOS 12.0 [-Wdeprecated-declarations]
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/IOKit.framework/Headers/IOKitLib.h:123:19: note: 'kIOMasterPortDefault' has been explicitly marked deprecated here
github.com/celo-org/celo-blockchain/crypto/secp256k1
# gopkg.in/olebedev/go-duktape.v3
In file included from _cgo_export.c:4:
debugger.go:23:13: warning: unused function '_duk_debugger_attach' [-Wunused-function]
Done building.
Run "./build/bin/geth" to launch geth.

$ ./build/bin/geth
<geth starts up and begins happily syncing>

```
### Related issues

N/A

### Backwards compatibility

N/A

### CODE REVIEW

**Comment by nategraf** [comment]
So I worked on this a bit more today and I think I got the build system fixed up, and was able to create the release artifacts. I will give them a try on this branch and work on getting the PR to celo-bls-go, and all its related repositories, merged. https://github.com/celo-org/celo-bls-go/pull/31

**Comment by nategraf** [comment]
@keefertaylor sorry for the delay, but I finally got all the publishing pipeline to work for `celo-bls-go` end-to-end and was able to release v0.3.1 with a fix to the infinite loop caught in the tests. You can give it a try to make sure it builds on your M1. This PR should be ready to merge and I will approve it now.

**Review by nategraf — APPROVED** [review]

**Comment by keefertaylor** [comment]
@nategraf I confirmed that this build on an M1 now. I also confirmed the node can start up and begin syncing blocks successfully, which wasn't the case before you fixed celo-bls-go. 

I think you can merge this!

**Comment by nategraf** [comment]
Looks like there are some build issues with iOS and Android. One of them are simply an out-of-date go.sum file, but there are also some issues with consuming the updated bls libraries. I am working on that now

**Comment by hbandura** [comment]
@keefertaylor seems that there are conflicts to resolve, if you can solve them I'll merge it

**Comment by palango** [comment]
@keefertaylor A fix for this problem has been merged in https://github.com/celo-org/celo-blockchain/pull/1946

**Comment by keefertaylor** [comment]
Thanks. I'll close this PR then.

**Pull request closed without merging**
