### PR TITLE
Fix incompatible abi for mycelo command

### LINKED ISSUE #1884: deployExchanges() doesn't work to generate Genesis
## Description
I tried to run localnet following to [Mycelo](https://github.com/celo-org/celo-blockchain/blob/master/cmd/mycelo/README.md).
But `execution reverted` happened after `mycelo genesis` command run.

There are some deploy functions in [deploy()](https://github.com/celo-org/celo-blockchain/blob/master/mycelo/genesis/genesis_state.go#L79), but only [ctx.deployExchanges](https://github.com/celo-org/celo-blockchain/blob/master/mycelo/genesis/genesis_state.go#L497) doesn't work.

## Current Behavior
`execution reverted` happened

## Context
after `mycelo genesis` command run

part [Mycelo](https://github.com/celo-org/celo-blockchain/blob/master/cmd/mycelo/README.md)

## Proposed Solution
after commenting out [ctx.deployExchanges](https://github.com/celo-org/celo-blockchain/blob/master/mycelo/genesis/genesis_state.go#L497), command works.

### PR DESCRIPTION
**Pull request by hiromaily**
### Description
This PR is to fix this issue https://github.com/celo-org/celo-blockchain/issues/1884

For now, ABI between contracts in celo-monorepo and mycelo in celo-blockchain has an inconsistency due to this changed PR in celo-monorepo https://github.com/celo-org/celo-monorepo/commit/1114edb5edc727f56453dab34a28a9f62667030b.

I referred to this README to generate `gen_abis.go`
https://github.com/celo-org/celo-blockchain/tree/master/mycelo/contract

### Related issues

- Fixes #1884

### CODE REVIEW

**Comment by nategraf** [comment]
@piersy I know you were looking into upgrading the contracts version. Could you take a look at this PR?

**Comment by hbandura** [comment]
@piersy do we want to use this v7 version of the contracts of mycelo? or just v6? I think in master rightt now v5 is being used

@hiromaily thanks for the fix, I actually encountered this problems a few days ago

**Comment by hiromaily** [comment]
@hbandura 
>  I think in master right now v5 is being used
I see. I didn't know version compatibility between celo-blockchain and celo-monorepo. I just found problem when using newest celo-monorepo commit version at master branch.
I can wait until v7 is released in master, thanks a lot :)

**Comment by JinboDev** [comment]
Be Advised no Admin or team will ever DM you or share you any link so you can only chat Here on Live Chat with Celo Agent  On LIVE SUPPORT[LIVE CHAT ](Be Advised no Admin or team will ever DM you or share you any link so you can only chat Here on Live Chat with Celo Agent  On LIVE SUPPORT)

**Comment by gastonponti** [comment]
@hiromaily Should be the String identifier of the StableToken, not the actual Exchange.
Already fixed in this PR #1938
Thanks for the contribution!

**Pull request closed without merging**
